CREATE TABLE LOAN_ACCOUNTS(ACCNO CHAR(4),CUST_NAME VARCHAR(15),LOAN_AMOUNT decimal(10,2),INSTALLMENT int,INT_RATE decimal(10,2),START_DATE date,INTEREST decimal(10,2));
DESCRIBE LOAN_ACCOUNTS;
ALTER TABLE LOAN_ACCOUNTS ADD COLUMN CATEGORY VARCHAR(1);
INSERT INTO LOAN_ACCOUNTS(ACCNO,CUST_NAME,LOAN_AMOUNT,INSTALLMENT,INT_RATE,START_DATE)VALUES
(1001,'R.K GUPTA',300000.00,36,12.00,'2009-07-19'),
(1002,'S.P SHARMA',500000.00,48,10.00,'2008-03-22'),
(1003,'K.P JAIN',300000.00,36,NULL,'2007-08-03'),
(1004,'M.P YADAV',800000.00,60,10.00,'2008-06-12'),
(1005,'S.P SINHA',200000.00,36,12.50,'2010-03-01'),
(1006,'P SHARMA',700000.00,60,12.50,'2008-05-06'),
(1007,'K.S DHALL',500000.00,48,NULL,'2008-05-03');
SELECT * FROM LOAN_ACCOUNTS;
update LOAN_ACCOUNTS set INT_RATE=11.50 where INT_RATE is null;
SELECT * FROM LOAN_ACCOUNTS;
Update Loan_Accounts set INT_RATE=INT_RATE + 0.5 where Loan_Amount > 400000;
SELECT * FROM LOAN_ACCOUNTS;
delete  from LOAN_ACCOUNTS where START_DATE < '2008-01-01';
SELECT * FROM LOAN_ACCOUNTS;
delete FROM LOAN_ACCOUNTS where CUST_NAME like 'K%';
SELECT * FROM LOAN_ACCOUNTS;
SELECT * FROM LOAN_ACCOUNTS where INSTALLMENT < 40;
SELECT ACCNO, Loan_amount FROM LOAN_ACCOUNTS where START_DATE < '2009-04-01';
SELECT Int_rate FROM LOAN_ACCOUNTS where START_DATE > '2009-04-01';
SELECT ACCNO, CUST_NAME, Loan_amount FROM LOAN_ACCOUNTS where CUST_NAME like '%SHARMA';
SELECT  Loan_amount FROM LOAN_ACCOUNTS where CUST_NAME like '%a';
SELECT ACCNO, CUST_NAME, Loan_amount FROM LOAN_ACCOUNTS where CUST_NAME like '%a%';
SELECT ACCNO, CUST_NAME, Loan_amount FROM LOAN_ACCOUNTS where NOT(CUST_NAME like '%P%');
DESCRIBE LOAN_ACCOUNTS;
SELECT * FROM LOAN_ACCOUNTS order by  Loan_amount asc;
SELECT * FROM LOAN_ACCOUNTS order by  START_DATE desc;
SELECT * FROM LOAN_ACCOUNTS order by Loan_amount, START_DATE desc;
SELECT * FROM LOAN_ACCOUNTS where CUST_NAME like 'K%';
SELECT * FROM LOAN_ACCOUNTS where INT_RATE is null;
 SELECT * FROM LOAN_ACCOUNTS where INT_RATE is not null;
SELECT distinct Loan_amount FROM LOAN_ACCOUNTS ;
SELECT * FROM LOAN_ACCOUNTS where START_DATE >'2008-12-31' and  INSTALLMENT >36;
SELECT CUST_NAME,LOAN_AMOUNT FROM LOAN_ACCOUNTS where LOAN_AMOUNT <500000 or  INT_RATE >12;
SELECT * FROM LOAN_ACCOUNTS where year(START_DATE)='2009';
SELECT * FROM LOAN_ACCOUNTS where LOAN_AMOUNT BETWEEN 400000 and  500000;
SELECT CUST_NAME,LOAN_AMOUNT FROM LOAN_ACCOUNTS where INSTALLMENT IN(26,36,48);
SELECT CUST_NAME,LOAN_AMOUNT,INT_RATE,CASE WHEN INT_RATE IS NULL THEN '0' ELSE INT_RATE END FROM LOAN_ACCOUNTS;
SELECT CUST_NAME,LOAN_AMOUNT,INT_RATE,CASE WHEN INT_RATE IS NULL THEN 'No interest' ELSE INT_RATE END FROM LOAN_ACCOUNTS;
